# Generated by Django 4.1.5 on 2025-03-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'table_date',
            },
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
            ],
            options={
                'db_table': 'table_edit',
            },
        ),
        migrations.CreateModel(
            name='s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
                ('one', models.CharField(max_length=100)),
                ('two', models.CharField(max_length=100)),
                ('three', models.CharField(max_length=100)),
                ('four', models.CharField(max_length=100)),
                ('five', models.CharField(max_length=100)),
                ('six', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('changes', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'table_savework',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('confirm_password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'table_signup',
            },
        ),
        
        migrations.AddField(
            model_name='s',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.signup'),
        ),
        migrations.AddField(
            model_name='edit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.signup'),
        ),
        migrations.AddField(
            model_name='date',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.signup'),
        ),
    ]
