# Generated by Django 4.1.5 on 2025-05-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_date_edit_s_signup_delete_blog_s_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
